name: CMake

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    name: Build ${{ matrix.project }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Cache vcpkg binaries
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: "%LOCALAPPDATA%/vcpkg/archives"
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('contrib/cmake/**') }}

    - name: Build
      run: cmake -DTRIPLET=x64-windows-mega -DEXTRA_ARGS="-DUSE_PDFIUM=0" -P build_from_scratch.cmake
      working-directory: "contrib/cmake"

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MEGAsdk-debug-${{ github.sha }}
        path: "build-x64-windows-mega"
